// src/config/admin.ts
// Generated by MiniMax M2.7

export const ADMIN_EMAILS: string[] = ['alex.e.peri@gmail.com'];

export function isAdmin(email: string, role: string): boolean {
  return (
    ADMIN_EMAILS.includes(email) ||
    role === 'admin' ||
    role === 'MANAGER'
  );
}
